spring.application.name=parking-iot
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/baidoxe?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=200220

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true